[package]
name = "Compounder"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1